Test

diff --git a/.github/workflows/test_workflow.yaml b/.github/workflows/test_workflow.yaml
--- a/.github/workflows/test_workflow.yaml
+++ b/.github/workflows/test_workflow.yaml
@@ -32,16 +32,15 @@ jobs:
           #fi
 
       - name: Checkout some folders
-        run: >-
-          set -x
-          echo "Restoring GitHub Actions workflows"
-          directories=".github/workflows"
-          git checkout master -- .github/workflows
-          if [ $? -eq 0 ]; then
-            echo "Successfully restored ${directories} directories"
-          else
-            echo "Couldn't restore ${directories}."
-            exit 1
+        run: >
+          echo "Restoring GitHub Actions workflows" \
+          directories=".github/workflows" \
+          git checkout master -- .github/workflows \
+          if [ $? -eq 0 ]; then \
+            echo "Successfully restored ${directories} directories" \
+          else \
+            echo "Couldn't restore ${directories}." \
+            exit 1 \
           fi
 
       #- name: checkout branch
