Test

diff --git a/.github/workflows/test_workflow.yaml b/.github/workflows/test_workflow.yaml
--- a/.github/workflows/test_workflow.yaml
+++ b/.github/workflows/test_workflow.yaml
@@ -50,7 +50,20 @@ jobs:
           #sparse-checkout: ".github/workflows"
 
       - name: Restore workflow
-        run: bash ./restore_workflow.sh
+        run: |
+          {
+            echo "#!/usr/bin/env bash"
+            echo "echo \"Restoring GitHub Actions workflows\""
+            echo "directories=\".github/workflows\""
+            echo "git checkout master -- \${directories}"
+            echo "if [ \$? -eq 0 ]; then"
+            echo "  echo \"Successfully restored \${directories} directories\""
+            echo "else"
+            echo "  echo \"Couldn't restore \${directories}.\""
+            echo "  exit 1"
+            echo "fi"
+          } > restore_workflow.sh
+          bash ./restore_workflow.sh
 
       - name: Checkout single file
         run: |
